name: CD

on:
  push:
    branches: ["main"]
    paths:
      - "app/**"
      - "infra/Dockerfile"
      - ".github/workflows/cd.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Configure AWS credentials from GitHub Secrets
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      # 3️⃣ Login to Amazon ECR
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      # 4️⃣ Build Docker image
      - name: Build Docker image
        run: docker build -t 914894372597.dkr.ecr.eu-central-1.amazonaws.com/aws-image-analizer-devops:latest -f infra/Dockerfile .

      # 5️⃣ Push Docker image to ECR
      - name: Push Docker image to ECR
        run: docker push 914894372597.dkr.ecr.eu-central-1.amazonaws.com/aws-image-analizer-devops:latest

      # 6️⃣ Create ECS Task Definition JSON
      - name: Update ECS Task Definition
        id: taskdef
        run: |
          echo "{
            \"family\": \"image-analyzer-task\",
            \"networkMode\": \"awsvpc\",
            \"requiresCompatibilities\": [\"FARGATE\"],
            \"cpu\": \"256\",
            \"memory\": \"512\",
            \"containerDefinitions\": [
              {
                \"name\": \"api\",
                \"image\": \"914894372597.dkr.ecr.eu-central
