name: CD
on:
  push:
    branches:
      - main
    paths:
      - app/**
      - infra/Dockerfile
      - .github/workflows/cd.yml
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
      - name: Build Docker image
        run: docker build -t 914894372597.dkr.ecr.eu-central-1.amazonaws.com/aws-image-analizer-devops:latest -f infra/Dockerfile .
      - name: Push Docker image to ECR
        run: docker push 914894372597.dkr.ecr.eu-central-1.amazonaws.com/aws-image-analizer-devops:latest
      - name: Update ECS Task Definition
        id: taskdef
        run: |
          echo "{
            \"family\": \"image-analyzer-task\",
            \"networkMode\": \"awsvpc\",
            \"requiresCompatibilities\": [\"FARGATE\"],
            \"cpu\": \"256\",
            \"memory\": \"512\",
            \"containerDefinitions\": [
              {
                \"name\": \"api\",
                \"image\": \"914894372597.dkr.ecr.eu-central-1.amazonaws.com/aws-image-analizer-devops:latest\",
                \"portMappings\": [{\"containerPort\": 5000}],
                \"environment\": [
                  {\"name\": \"S3_BUCKET\", \"value\": \"tatiana-photo-analyzer3\"},
                  {\"name\": \"DYNAMO_TABLE\", \"value\": \"ImageLabels\"}
                ]
              }
            ]
          }" > task-def.json
      - name: Register Task Definition
        run: aws ecs register-task-definition --cli-input-json file://task-def.json
      - name: Update ECS Service
        run: |
          aws ecs update-service \
            --cluster image-analyzer-cluster \
            --service image-analyzer-service \
            --force-new-deployment
